### ISSUE TITLE
Gmond and modpython.so

### ISSUE THREAD

**Issue by RolT** [ganglia/gmond_python_modules#151]
I'm not sure if this is the good place to post this one :
I get a segmentation fault the module modpython.so is loaded. The cluster is running on CentOS 6.4, I installed everything from the epel repos, yet I cant make this work.

Here is what I added to the gmond config file

```
modules {
  ...
  module {
    name = "python_module"
    path = "/usr/lib64/ganglia/modpython.so"
    params = "/usr/lib64/ganglia/python_modules/"
  }
}
include ('/etc/ganglia/conf.d/*.pyconf')
```

I did not add any python modules, I tried removing the already installed ones, nothing worked.
Python 2.6.6, gcc 4.7.0, gmond & gmetad 3.7.1

Any advices ?

**Comment by app-genesis** [comment]
Any progress on that?

**Comment by RolT** [comment]
I really dont remember. I dont think I solved it in the end.
